<a href="https://colab.research.google.com/github/AiWriter404/AI-With-Python-Digiskills/blob/main/ai_with_python_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Topic 57 Import & Export - CSV, Excel & JSON
!pip install openpyxl
!pip install pandas

Requirement already satisfied: openpyxl in c:\users\aiwri\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\aiwri\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: pandas in c:\users\aiwri\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aiwri\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aiwri\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aiwri\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aiwri\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aiwri\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import openpyxl

In [ ]:
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [ ]:
clean_df=df[df["Sales"]>0]
subset=clean_df[["Date","Category","Sales","Region"]]

In [ ]:
subset.to_excel("subset_sales.xlsx",sheet_name='sales')
subset.to_json("Subset_sales.json",
               orient="records",
               date_format="iso")
print("File Exported:")
subset.info()

File Exported:
<class 'pandas.core.frame.DataFrame'>
Index: 1778 entries, 0 to 1824
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1778 non-null   datetime64[ns]
 1   Category  1774 non-null   category
 2   Sales     1778 non-null   float64
 3   Region    1775 non-null   category
dtypes: category(2), datetime64[ns](1), float64(1)
memory usage: 110.2 KB

In [ ]:
# Topic 58 Handling Data Types & Type Conversion
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category"

    }
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB

In [ ]:
# Convet age to Numeric
df['Profit']=pd.to_numeric(df['Profit'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB

In [ ]:
# Convert City to Category
df['Region']=df['Region'].astype('category')
df.info()
print(df['Region'].memory_usage(deep=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB
2395

In [ ]:
# Topic 59 Handling Missing Data
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [ ]:
# Detect missing Values
print(df.isna().sum())

Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64

In [ ]:
# Fill missing age with mean
df['Quantity']=pd.to_numeric(df['Quantity'])
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mode()[0])

In [ ]:
# fill missing value with median
df['Sales']=df['Sales'].fillna(df['Sales'].median())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1825 non-null   float64
 3   Quantity  1825 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [ ]:
df.isna().sum()

Date        0
Category    4
Sales       0
Quantity    0
Profit      0
Region      5
dtype: int64

In [ ]:
df.dropna(subset=['Region'],inplace=True)

In [ ]:
# Remove missing values in region and category
df['Category'] = df['Category'].cat.add_categories("0").fillna("0")
df['Region'] = df['Region'].cat.add_categories("0").fillna("0")

In [ ]:
df.isna().sum()

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1820 non-null   datetime64[ns]
 1   Category  1820 non-null   category
 2   Sales     1820 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1820 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 75.2 KB

In [ ]:
# Topic 60 String & Text Cleaning
import pandas as pd

In [ ]:
df=pd.DataFrame({
    'Category': [' Electronics ', 'furnitures','Home-appliances',
                 'electornics','FURNITURE']
                 })
print(df)

          Category
0     Electronics
1       furnitures
2  Home-appliances
3      electornics
4        FURNITURE

In [ ]:
# Strip Spaces and convert to lowercase
df['Category_clean'] =df['Category'].str.strip().str.lower()
print(df)

          Category   Category_clean
0     Electronics       electronics
1       furnitures       furnitures
2  Home-appliances  home-appliances
3      electornics      electornics
4        FURNITURE        furniture

In [ ]:
# Replace hyphense with space
df['Category_clean'] = df['Category_clean'].str.replace('-', ' ')
print(df)

          Category   Category_clean
0     Electronics       electronics
1       furnitures       furnitures
2  Home-appliances  home appliances
3      electornics      electornics
4        FURNITURE        furniture

In [ ]:
# Topic 61 Sorting & Ranking Data
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)
df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [ ]:
df=pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)
df.tail()

           Date     Category        Sales  Quantity      Profit Region
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

In [ ]:
df_sorted=df.sort_values(by=['Quantity','Sales'],ascending=[False,True])
print("Sorted the DataFrame")
df_sorted.head()

Sorted the DataFrame

           Date    Category       Sales  Quantity      Profit Region
312  2023-03-04  Home Goods    0.000000      19.0    0.000000   West
528  2023-04-16      Sports    0.000000      19.0  270.577388   West
1708 2023-12-08      Sports  227.942727      19.0   61.534381  North
571  2023-04-25    Clothing  361.006937      19.0   57.285585   West
1213 2023-08-31      Sports  368.305917      19.0   73.419555   West

In [ ]:
# Rank Salary within Age Groups
df['Sales_rank'] = df.groupby('Quantity')['Sales'].rank(method='dense',
                                                        ascending=False)
print("\nSales Rank within Quantity Groups:\n",df)

Sales Rank within Quantity Groups:
            Date     Category        Sales  Quantity      Profit Region  \
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

      Sales_rank
0           29.0
1           56.0
2            7.0
3           24.0
4           68.0
...          ...
1820        30.0
1821        88.0
1822        32.0
1823        38.0
1824        73.0

[1825 rows x 7 columns]

In [ ]:
# Topic 62 Merging & Joining DataFrames
import pandas as pd

In [ ]:
# Samples DataFrames
custormers=pd.DataFrame({
    'CustomerID': [1,2,3],
    'Name':['Alina', 'Bobi','Charlie']
})
orders=pd.DataFrame({
    'OrderID':[101,102,103,104,],
    'CustomerID':[1,2,3,4],
    'Amount':[250,150,200,300]
    })

In [ ]:
# Inner Merge on CustomerID
df_inner = pd.merge(customers, orders, on='CustomerID', how='inner')
print("Inner Merge:\n", df_inner)

NameError: name 'customers' is not defined

In [ ]:
import pandas as pd
# Samples DataFrames
custormers=pd.DataFrame({
    'CustomerID': [1,2,3],
    'Name':['Alina', 'Bobi','Charlie']
})
orders=pd.DataFrame({
    'OrderID':[101,102,103,104,],
    'CustomerID':[1,2,3,4],
    'Amount':[250,150,200,300]
    })

In [ ]:
# Inner Merge
df_inner=pd.merge(customers,orders, on='CustomerID', how='inner')
print("Inner Merge:\n", df_inner)

NameError: name 'customers' is not defined

In [ ]:
# Left Merge
df_left=pd.merge(customers,orders, on='CustomerID', how='left')
print("\nLeft Merge\n", df_left)

NameError: name 'customers' is not defined

In [ ]:
# Concatenate Row Examples
df_concat=pd.concat([customers,customers])
print("\nConcatenated Rows:\n",df_concat)

NameError: name 'customers' is not defined

In [ ]:
#Topic 63 Applying Functions - apply, map & pipe
df=pd.read_csv("ecommerce_sales_analytics_5000", parse_dates=["order_date"])
df.info()

FileNotFoundError: [Errno 2] No such file or directory: 'ecommerce_sales_analytics_5000'

In [ ]:
# map() - label high value orders
df["payment_type"]=df["payment_method"].map({
    "Card": "Digital",
    "Wallet": "Digital",
    "Cod": "Cash"
})
# Each Value mapped induisually fast and simple

KeyError: 'payment_method'

In [ ]:
# Verify
df["Payment_type"].unique() # check unique value

KeyError: 'Payment_type'

In [ ]:
df[["Pamymet_method", "Payment_type"]].head() # compare before and after

KeyError: "None of [Index(['Pamymet_method', 'Payment_type'], dtype='object')] are in the [columns]"

In [ ]:
# Business sanity check
df.groupby("Payment_type").size()

KeyError: 'Payment_type'

In [ ]:
# Apply Creat Revenue Category
def revenue_category(row):
    if row ["revenue"] > 500:
        return "Hight"
    elif row ["revenue"] >=200:
        return "Medium"
    else:
        return "Low"
df["revenue_category"]=df.apply(revenue_category, axis=1)
# why apply decisions on multiple columns

KeyError: 'revenue'

In [ ]:
# verify
df["revenue_category"].value_count()
# check categories

KeyError: 'revenue_category'

In [ ]:
df[["revenue", "revenue_category"]].sample(10)
# revenue > 500 is high
# revenue between 200-500 medium
# < 200 low

KeyError: "None of [Index(['revenue', 'revenue_category'], dtype='object')] are in the [columns]"

In [ ]:
# Pipe () Method chaining
def add_profit(data):
    data["profit"]=data["revenue"] *0.20
    return data
def add_net_revenue(data):
    data["net_revenue"]=data["revenue"] - data["profit"]
    return data
def = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)

SyntaxError: invalid syntax (4070770355.py, line 8)

In [ ]:
# Verify
df[["revenue","profit", "net_revenue"]].head()
# check new columns

KeyError: "None of [Index(['revenue', 'profit', 'net_revenue'], dtype='object')] are in the [columns]"

In [ ]:
# Topic 64 EDA Key Questions & Mindset
# All is theory about EDA

In [ ]:
# Topic 65 Descriptive Stats & Data Distributions
df=pd.read_csv("ecommerce_sales_analytics_5000", parse_dates=["order_date"])
df.info()

FileNotFoundError: [Errno 2] No such file or directory: 'ecommerce_sales_analytics_5000'

In [ ]:
# Verify Dataset before analysis
df.shape

(1825, 7)

In [ ]:
# Core descriptive statistics (describe())
df.describe()

,Date,Sales,Quantity,Profit,Sales_rank
count,1825,1823.000000,1820.000000,1825.000000,1818.000000
mean,2023-07-02 00:00:00.000000256,980.482677,10.053846,248.696130,48.484048
min,2023-01-01 00:00:00,0.000000,0.000000,0.000000,1.000000
25%,2023-04-02 00:00:00,784.071354,5.000000,156.916498,24.000000
50%,2023-07-02 00:00:00,997.725134,10.000000,229.344557,48.000000
75%,2023-10-01 00:00:00,1208.512721,15.000000,324.867847,72.000000
max,2023-12-31 00:00:00,1888.932537,19.000000,703.228418,109.000000
std,NaN,336.756618,5.515370,118.159627,27.970206

In [ ]:
# For revenue value
df[["unit_price","revenue"]].describe()

KeyError: "None of [Index(['unit_price', 'revenue'], dtype='object')] are in the [columns]"

In [ ]:
# Quantiles
df["revenue"].quantile([0.25,0.5,0.75])

KeyError: 'revenue'

In [ ]:
# Identifying skewness
df["revenue"].mead(), df["revenue"].median()

KeyError: 'revenue'

In [ ]:
# Possitive Value right skew
df["revenue"].skew()

KeyError: 'revenue'

In [ ]:
# Category level descriptive statistics
df.groupby("product_category")["revenue"].describe
# do different products categories behave different

KeyError: 'product_category'

In [ ]:
# using IQR to undestand spread
Q1=df["revenue"].quantile(0.25)
Q3=df["revenue"].quantile(0.75)
IQR = Q3-Q1
# helps understand normal range
# perhaps us for outlier detection (next lesson)

KeyError: 'revenue'

In [ ]:
(Q3>Q1) and (IQR > 0)

NameError: name 'Q3' is not defined

In [ ]:
# Topic 66 Working with Datetime & Time Series Data
import pandas as pd

In [ ]:
df=pd.read_csv("ecommerce_sales_analytics_5000", parse_dates=["order_date"])

FileNotFoundError: [Errno 2] No such file or directory: 'ecommerce_sales_analytics_5000'

In [ ]:
# Setting Date Time Index
df=df.set_index("order_date")
df.index

KeyError: "None of ['order_date'] are in the columns"

In [ ]:
# Monthly Revenue Analysis
monthly_revenue = df["revenue"].resample("ME").sum()
monthly_revenue

KeyError: 'revenue'

In [ ]:
# Trend interpretation
monthl_revenue.pct_change()

NameError: name 'monthl_revenue' is not defined

In [ ]:
# Verify
monthly_revenue.index.is_monotonic_increasing

NameError: name 'monthly_revenue' is not defined

In [ ]:
pritn(monthly_revenue.sum(),df["revenue"].sum())# Check
monthy_revenue.sum()<=df["revenue"].sum()